{
  "contest": 221,
  "handle": "fatherOfBlocks",
  "risk": "2",
  "title": "In the withdraw function it is possible to reach incorrect internal state values",
  "issueId": 48,
  "issueUrl": "https://github.com/code-423n4/2023-03-zksync-findings/issues/48"
}